In [1]:
#Import Libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/cars.csv')
df

symboling normalized-losses         make fuel-type   body-style  \
0            3                 ?  alfa-romero       gas  convertible   
1            3                 ?  alfa-romero       gas  convertible   
2            1                 ?  alfa-romero       gas    hatchback   
3            2               164         audi       gas        sedan   
4            2               164         audi       gas        sedan   
..         ...               ...          ...       ...          ...   
200         -1                95        volvo       gas        sedan   
201         -1                95        volvo       gas        sedan   
202         -1                95        volvo       gas        sedan   
203         -1                95        volvo    diesel        sedan   
204         -1                95        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

    horsepower  city-mpg  highway-mpg  price  
0          111        21           27  13495  
1          111        21           27  16500  
2          154        19           26  16500  
3          102        24           30  13950  
4          115        18           22  17450  
..         ...       ...          ...    ...  
200        114        23           28  16845  
201        160        19           25  19045  
202        134        18           23  21485  
203        106        26           27  22470  
204        114        19           25  22625  

[205 rows x 15 columns]

In [2]:
#Load dataset

# EDA

In [3]:
df.describe()

symboling       width      height  engine-size    city-mpg  \
count  205.000000  205.000000  205.000000   205.000000  205.000000   
mean     0.834146   65.907805   53.724878   126.907317   25.219512   
std      1.245307    2.145204    2.443522    41.642693    6.542142   
min     -2.000000   60.300000   47.800000    61.000000   13.000000   
25%      0.000000   64.100000   52.000000    97.000000   19.000000   
50%      1.000000   65.500000   54.100000   120.000000   24.000000   
75%      2.000000   66.900000   55.500000   141.000000   30.000000   
max      3.000000   72.300000   59.800000   326.000000   49.000000   

       highway-mpg         price  
count   205.000000    205.000000  
mean     30.751220  13227.478049  
std       6.886443   7902.651615  
min      16.000000   5118.000000  
25%      25.000000   7788.000000  
50%      30.000000  10345.000000  
75%      34.000000  16500.000000  
max      54.000000  45400.000000

In [4]:
df.replace('?',np.nan,inplace=True)

In [5]:
df.isna().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
si = SimpleImputer(strategy='median')

In [8]:
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3               NaN  alfa-romero       gas  convertible   
1          3               NaN  alfa-romero       gas  convertible   
2          1               NaN  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [10]:
df.iloc[:,[1,11]] = si.fit_transform(df.iloc[:,[1,11]])

In [11]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [12]:
df.head()

symboling  normalized-losses         make fuel-type   body-style  \
0          3              115.0  alfa-romero       gas  convertible   
1          3              115.0  alfa-romero       gas  convertible   
2          1              115.0  alfa-romero       gas    hatchback   
3          2              164.0         audi       gas        sedan   
4          2              164.0         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

   horsepower  city-mpg  highway-mpg  price  
0       111.0        21           27  13495  
1       111.0        21           27  16500  
2       154.0        19           26  16500  
3       102.0        24           30  13950  
4       115.0        18           22  17450

In [13]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [18]:
cat_cols = df.select_dtypes(object).columns

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
oe = OrdinalEncoder()

In [21]:
df[cat_cols] = oe.fit_transform(df[cat_cols])

In [22]:
df

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
0            3              115.0   0.0        1.0         0.0           2.0   
1            3              115.0   0.0        1.0         0.0           2.0   
2            1              115.0   0.0        1.0         2.0           2.0   
3            2              164.0   1.0        1.0         3.0           1.0   
4            2              164.0   1.0        1.0         3.0           0.0   
..         ...                ...   ...        ...         ...           ...   
200         -1               95.0  21.0        1.0         3.0           2.0   
201         -1               95.0  21.0        1.0         3.0           2.0   
202         -1               95.0  21.0        1.0         3.0           2.0   
203         -1               95.0  21.0        0.0         3.0           2.0   
204         -1               95.0  21.0        1.0         3.0           2.0   

     engine-location  width  height  engine-type  engine-size  horsepower  \
0                0.0   64.1    48.8          0.0          130       111.0   
1                0.0   64.1    48.8          0.0          130       111.0   
2                0.0   65.5    52.4          5.0          152       154.0   
3                0.0   66.2    54.3          3.0          109       102.0   
4                0.0   66.4    54.3          3.0          136       115.0   
..               ...    ...     ...          ...          ...         ...   
200              0.0   68.9    55.5          3.0          141       114.0   
201              0.0   68.8    55.5          3.0          141       160.0   
202              0.0   68.9    55.5          5.0          173       134.0   
203              0.0   68.9    55.5          3.0          145       106.0   
204              0.0   68.9    55.5          3.0          141       114.0   

     city-mpg  highway-mpg  price  
0          21           27  13495  
1          21           27  16500  
2          19           26  16500  
3          24           30  13950  
4          18           22  17450  
..        ...          ...    ...  
200        23           28  16845  
201        19           25  19045  
202        18           23  21485  
203        26           27  22470  
204        19           25  22625  

[205 rows x 15 columns]

In [23]:
x = df.iloc[:,:-1]
y = df['price']

In [24]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=1)

In [25]:
lr = LinearRegression()
lr.fit(xtrain,ytrain)
ypred = lr.predict(xtest)

In [26]:
lr.score(xtrain,ytrain),lr.score(xtest,ytest)

(0.8504229026078213, 0.7964854785429523)

In [27]:
lr.coef_

array([ 5.71727164e+01,  4.76320989e-01, -2.01309566e+02, -6.22705136e+02,
       -1.63712110e+02,  1.88863899e+03,  1.63884484e+04,  7.90632094e+02,
        3.61221503e+02,  2.81207534e+02,  9.82290864e+01, -1.06474945e+01,
        3.08435166e+02, -4.17126915e+02])

In [28]:
lr.intercept_

-64935.1135797824

# Lasso

In [29]:
l1 = Lasso(alpha=1)

l1.fit(xtrain,ytrain)
y = l1.predict(xtest)

In [30]:
l1.score(xtrain,ytrain),l1.score(xtest,ytest)

(0.8504215478243033, 0.7966615211575689)

# Hyperparameter Tuning

In [34]:
for i in range(100,200,10):
    l1 = Lasso(alpha=i)
    l1.fit(xtrain,ytrain)
    print(f"{i} {l1.score(xtrain,ytrain)} {l1.score(xtest,ytest)}")

100 0.8372483974026499 0.8092040910955615
110 0.8345477714936768 0.8101055942385992
120 0.8315898643306087 0.8109242812985726
130 0.8283747703082013 0.8116601017520375
140 0.8249024913515863 0.8123130602354285
150 0.8211730520262539 0.8128831566524961
160 0.8171860531186915 0.8133704442145949
170 0.812942107429732 0.8137748292356427
180 0.8084404898252787 0.8140963672263584
190 0.8036814832401015 0.8143350086553349


In [33]:
l1 = Lasso(alpha=175)
l1.fit(xtrain,ytrain)
l1.score(xtrain,ytrain),l1.score(xtest,ytest)

(0.8107234361496892, 0.8139459609474126)

In [35]:
l1.coef_

array([  22.93189969,   -0.        , -170.73691358,   -0.        ,
       -382.09249157, 1186.68861277, 2775.90738975,  353.08826462,
        459.014838  ,  299.47120844,  114.54903172,   13.01120437,
         48.51490841, -137.56175995])

In [36]:
x.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'body-style',
       'drive-wheels', 'engine-location', 'width', 'height', 'engine-type',
       'engine-size', 'horsepower', 'city-mpg', 'highway-mpg'],
      dtype='object')

# Ridge 

In [38]:
for i in range(1,10):
    l2 = Ridge(alpha=i)
    l2.fit(xtrain,ytrain)
    print(f"{i} {l2.score(xtrain,ytrain)} {l2.score(xtest,ytest)}")

1 0.8435840853399225 0.8075632224690532
2 0.8356695734845094 0.8112192014374253
3 0.8296379623431073 0.8129299663310143
4 0.8250699092246865 0.8138839096972442
5 0.8215093087765016 0.8144682684596011
6 0.8186486103834848 0.814843562726523
7 0.816288257302081 0.8150880725612083
8 0.8142964263180523 0.815244730507158
9 0.8125835227290971 0.8153392574436444


In [39]:
l2 = Ridge(alpha=7)
l2.fit(xtrain,ytrain)
l2.score(xtrain,ytrain),l2.score(xtest,ytest)

(0.816288257302081, 0.8150880725612083)

In [40]:
l2.coef_

array([ 2.31139279e+02, -3.29204695e+00, -1.90126861e+02, -1.01249352e+03,
       -6.04047656e+02,  1.71736131e+03,  3.40160377e+03,  3.91530395e+02,
        5.57861287e+02,  5.13867686e+02,  1.02968876e+02,  2.01227011e+01,
        2.13425523e+02, -2.79915768e+02])

# Elastic Net

In [41]:
en = ElasticNet()

en.fit(xtrain,ytrain)
en.score(xtrain,ytrain),en.score(xtest,ytest)

(0.7866253599240466, 0.809826481725613)