In [1]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model import LinearRegression, Lasso,Ridge,ElasticNet
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv(r"C:\Users\Aishwarya\Desktop\Datasets\cars.csv")
df

symboling normalized-losses         make fuel-type   body-style  \
0            3                 ?  alfa-romero       gas  convertible   
1            3                 ?  alfa-romero       gas  convertible   
2            1                 ?  alfa-romero       gas    hatchback   
3            2               164         audi       gas        sedan   
4            2               164         audi       gas        sedan   
..         ...               ...          ...       ...          ...   
200         -1                95        volvo       gas        sedan   
201         -1                95        volvo       gas        sedan   
202         -1                95        volvo       gas        sedan   
203         -1                95        volvo    diesel        sedan   
204         -1                95        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

    horsepower  city-mpg  highway-mpg  price  
0          111        21           27  13495  
1          111        21           27  16500  
2          154        19           26  16500  
3          102        24           30  13950  
4          115        18           22  17450  
..         ...       ...          ...    ...  
200        114        23           28  16845  
201        160        19           25  19045  
202        134        18           23  21485  
203        106        26           27  22470  
204        114        19           25  22625  

[205 rows x 15 columns]

In [3]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   body-style         205 non-null    object 
 5   drive-wheels       205 non-null    object 
 6   engine-location    205 non-null    object 
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object 
 10  engine-size        205 non-null    int64  
 11  horsepower         205 non-null    object 
 12  city-mpg           205 non-null    int64  
 13  highway-mpg        205 non-null    int64  
 14  price              205 non-null    int64  
dtypes: float64(2), int64(5), object(8)
memory usage: 24.1+ KB


In [5]:
df.replace('?',np.nan,inplace=True)

In [7]:
df.isna().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [8]:
si = SimpleImputer()
df[['normalized-losses','horsepower']] = si.fit_transform(df[['normalized-losses','horsepower']])

In [9]:
df.head()

symboling  normalized-losses         make fuel-type   body-style  \
0          3              122.0  alfa-romero       gas  convertible   
1          3              122.0  alfa-romero       gas  convertible   
2          1              122.0  alfa-romero       gas    hatchback   
3          2              164.0         audi       gas        sedan   
4          2              164.0         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

   horsepower  city-mpg  highway-mpg  price  
0       111.0        21           27  13495  
1       111.0        21           27  16500  
2       154.0        19           26  16500  
3       102.0        24           30  13950  
4       115.0        18           22  17450

In [10]:
df['make'].nunique()

22

# Encoding

In [12]:
cat_cols = df.select_dtypes(object).columns
cat_cols

Index(['make', 'fuel-type', 'body-style', 'drive-wheels', 'engine-location',
       'engine-type'],
      dtype='object')

In [13]:
oe = OrdinalEncoder()

In [14]:
df[cat_cols] = oe.fit_transform(df[cat_cols])
df

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
0            3              122.0   0.0        1.0         0.0           2.0   
1            3              122.0   0.0        1.0         0.0           2.0   
2            1              122.0   0.0        1.0         2.0           2.0   
3            2              164.0   1.0        1.0         3.0           1.0   
4            2              164.0   1.0        1.0         3.0           0.0   
..         ...                ...   ...        ...         ...           ...   
200         -1               95.0  21.0        1.0         3.0           2.0   
201         -1               95.0  21.0        1.0         3.0           2.0   
202         -1               95.0  21.0        1.0         3.0           2.0   
203         -1               95.0  21.0        0.0         3.0           2.0   
204         -1               95.0  21.0        1.0         3.0           2.0   

     engine-location  width  height  engine-type  engine-size  horsepower  \
0                0.0   64.1    48.8          0.0          130       111.0   
1                0.0   64.1    48.8          0.0          130       111.0   
2                0.0   65.5    52.4          5.0          152       154.0   
3                0.0   66.2    54.3          3.0          109       102.0   
4                0.0   66.4    54.3          3.0          136       115.0   
..               ...    ...     ...          ...          ...         ...   
200              0.0   68.9    55.5          3.0          141       114.0   
201              0.0   68.8    55.5          3.0          141       160.0   
202              0.0   68.9    55.5          5.0          173       134.0   
203              0.0   68.9    55.5          3.0          145       106.0   
204              0.0   68.9    55.5          3.0          141       114.0   

     city-mpg  highway-mpg  price  
0          21           27  13495  
1          21           27  16500  
2          19           26  16500  
3          24           30  13950  
4          18           22  17450  
..        ...          ...    ...  
200        23           28  16845  
201        19           25  19045  
202        18           23  21485  
203        26           27  22470  
204        19           25  22625  

[205 rows x 15 columns]

In [15]:
sc = StandardScaler()

In [16]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [33]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'body-style',
       'drive-wheels', 'engine-location', 'width', 'height', 'engine-type',
       'engine-size', 'horsepower', 'city-mpg', 'highway-mpg', 'price'],
      dtype='object')

In [34]:
x = sc.fit_transform(x)
x = pd.DataFrame(x, columns=['symboling', 'normalized-losses', 'make', 'fuel-type', 'body-style',
       'drive-wheels', 'engine-location', 'width', 'height', 'engine-type',
       'engine-size', 'horsepower', 'city-mpg', 'highway-mpg'])
x

symboling  normalized-losses      make  fuel-type  body-style  \
0     1.743470       3.466062e-17 -1.948256   0.328798   -3.050975   
1     1.743470       3.466062e-17 -1.948256   0.328798   -3.050975   
2     0.133509       3.466062e-17 -1.948256   0.328798   -0.717207   
3     0.938490       1.328961e+00 -1.788499   0.328798    0.449677   
4     0.938490       1.328961e+00 -1.788499   0.328798    0.449677   
..         ...                ...       ...        ...         ...   
200  -1.476452      -8.543319e-01  1.406641   0.328798    0.449677   
201  -1.476452      -8.543319e-01  1.406641   0.328798    0.449677   
202  -1.476452      -8.543319e-01  1.406641   0.328798    0.449677   
203  -1.476452      -8.543319e-01  1.406641  -3.041381    0.449677   
204  -1.476452      -8.543319e-01  1.406641   0.328798    0.449677   

     drive-wheels  engine-location     width    height  engine-type  \
0        1.213330        -0.121867 -0.844782 -2.020417    -2.865105   
1        1.213330        -0.121867 -0.844782 -2.020417    -2.865105   
2        1.213330        -0.121867 -0.190566 -0.543527     1.886890   
3       -0.589081        -0.121867  0.136542  0.235942    -0.013908   
4       -2.391492        -0.121867  0.230001  0.235942    -0.013908   
..            ...              ...       ...       ...          ...   
200      1.213330        -0.121867  1.398245  0.728239    -0.013908   
201      1.213330        -0.121867  1.351515  0.728239    -0.013908   
202      1.213330        -0.121867  1.398245  0.728239     1.886890   
203      1.213330        -0.121867  1.398245  0.728239    -0.013908   
204      1.213330        -0.121867  1.398245  0.728239    -0.013908   

     engine-size  horsepower  city-mpg  highway-mpg  
0       0.074449    0.171065 -0.646553    -0.546059  
1       0.074449    0.171065 -0.646553    -0.546059  
2       0.604046    1.261807 -0.953012    -0.691627  
3      -0.431076   -0.057230 -0.186865    -0.109354  
4       0.218885    0.272529 -1.106241    -1.273900  
..           ...         ...       ...          ...  
200     0.339248    0.247163 -0.340094    -0.400490  
201     0.339248    1.414003 -0.953012    -0.837195  
202     1.109571    0.754485 -1.106241    -1.128332  
203     0.435538    0.044234  0.119594    -0.546059  
204     0.339248    0.247163 -0.953012    -0.837195  

[205 rows x 14 columns]

# Model Building

In [18]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.25,random_state=1)

# Linear Regression

In [19]:
lr = LinearRegression()
lr.fit(xtrain,ytrain)
ypred = lr.predict(xtest)
print(lr.score(xtrain,ytrain))
print(lr.score(xtest,ytest))

0.8426404740417467
0.8174935371483152


In [20]:
lr.coef_

array([   17.25303655,     4.79335609, -1188.25134623,   -68.60684114,
        -156.8647891 ,  1084.90518744,  1923.38798081,  1671.40036556,
         786.55498954,   381.18938257,  4046.45606814,  -442.50497236,
        1395.19725703, -2298.83591186])

In [21]:
lr.intercept_

13085.49253371863

In [23]:
print(mean_squared_error(ytest,ypred))
print(np.sqrt(mean_squared_error(ytest,ypred)))

12228004.50250261
3496.8563743028694


# Lasso Regression

In [24]:
lasso = Lasso()
lasso.fit(xtrain,ytrain)
print(lasso.score(xtrain,ytrain))
print(lasso.score(xtest,ytest))

0.8426389275234948
0.8176044872313545


In [26]:
for i in range(100,200):
    lasso = Lasso(alpha=i)
    lasso.fit(xtrain,ytrain)
    print(f"{i} {lasso.score(xtrain,ytrain)} {lasso.score(xtest,ytest)}")

100 0.8383929207238536 0.8237805071712705
101 0.8383714809341707 0.8237689132189763
102 0.8383498277364144 0.8237571663276865
103 0.8383279611082594 0.8237452665472498
104 0.8383058809836941 0.8237332140219924
105 0.8382837038932145 0.823721875602608
106 0.8382611956405709 0.8237095037594837
107 0.8382384758788841 0.823696987643583
108 0.8382155436362211 0.8236843228971659
109 0.8381923979954164 0.823671505208569
110 0.8381690389599711 0.8236585345747535
111 0.8381454665222472 0.8236454110027838
112 0.8381216807101902 0.8236321340003632
113 0.8380976815323601 0.8236187024112431
114 0.8380734689969039 0.8236051169624502
115 0.8380490430609622 0.8235913785748314
116 0.8380244037245346 0.8235774872483869
117 0.8379995509876212 0.8235634429831165
118 0.8379744848409989 0.8235492457941186
119 0.8379492059771121 0.8235348984824926
120 0.8379237149322113 0.8235204028290763
121 0.8378980105188847 0.823505754244833
122 0.8378720927371326 0.8234909527297625
123 0.8378459615960292 0.8234759981643

In [27]:
l1 = Lasso(alpha=199)

l1.fit(xtrain,ytrain)
print(l1.score(xtrain,ytrain))
print(l1.score(xtest,ytest))

0.8352359236704644
0.8218926869422283


In [29]:
lr.coef_

array([   17.25303655,     4.79335609, -1188.25134623,   -68.60684114,
        -156.8647891 ,  1084.90518744,  1923.38798081,  1671.40036556,
         786.55498954,   381.18938257,  4046.45606814,  -442.50497236,
        1395.19725703, -2298.83591186])

In [28]:
l1.coef_

array([  -0.        ,    0.        , -932.77085464,  -55.56241125,
         -0.        ,  912.85071909, 1656.1421693 , 1538.60758589,
        587.82745736,  223.57959712, 3895.08588367,    0.        ,
         -0.        , -734.47668879])

In [35]:
features = pd.DataFrame(l1.coef_).T
features.columns = x.columns
features

symboling  normalized-losses        make  fuel-type  body-style  \
0       -0.0                0.0 -932.770855 -55.562411        -0.0   

   drive-wheels  engine-location        width      height  engine-type  \
0    912.850719      1656.142169  1538.607586  587.827457   223.579597   

   engine-size  horsepower  city-mpg  highway-mpg  
0  3895.085884         0.0      -0.0  -734.476689

# Ridge Regression

In [37]:
for i in range(10,100):
    l2 = Ridge(alpha=i)
    l2.fit(xtrain,ytrain)
    print(f"{i} {l2.score(xtrain,ytrain)} {l2.score(xtest,ytest)}")

10 0.8382513325569908 0.8227160379230571
11 0.8377130549154546 0.8227072484490273
12 0.837171784239692 0.8226520961352164
13 0.83662849401716 0.8225562468778781
14 0.8360839420379627 0.8224245039194631
15 0.8355387182716452 0.8222609650731116
16 0.8349932811975809 0.8220691464554246
17 0.8344479857501791 0.8218520809812341
18 0.8339031050269655 0.821612397526915
19 0.8333588472779054 0.8213523850905019
20 0.8328153692801158 0.8210740451795412
21 0.8322727869175006 0.820779134874576
22 0.8317311835828203 0.820469202445878
23 0.8311906168728274 0.8201456169787504
24 0.8306511239383914 0.819809593145765
25 0.8301127257699885 0.8194622120235938
26 0.829575430637093 0.8191044386675062
27 0.8290392368527305 0.818737137013753
28 0.828504134998042 0.8183610825686676
29 0.8279701097134898 0.8179769732558053
30 0.8274371411413661 0.8175854387232493
31 0.8269052060870512 0.8171870483581578
32 0.8263742789529538 0.8167823182115845
33 0.8258443324883766 0.8163717170011624
34 0.8253153383900954 0.81

In [38]:
l2 = Ridge(alpha=45)
l2.fit(xtrain,ytrain)
print(l2.score(xtrain,ytrain))
print(l2.score(xtest,ytest))

0.8195511565198612
0.8111109488824153


In [39]:
l2.coef_

array([-194.30978175,   34.62508051, -935.9039786 , -463.55138064,
       -267.85788861,  984.98283582, 1421.05863223, 1376.89188167,
        680.97960365,  416.54018662, 2435.5641169 ,  758.34601021,
       -405.88907264, -811.55883293])

# Elastic Net 

In [40]:
elastic = ElasticNet()
elastic.fit(xtrain,ytrain)
print(elastic.score(xtrain,ytrain))
print(elastic.score(xtest,ytest))

0.8033783817373423
0.7959913488083025
