In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.metrics import r2_score
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv(r"C:\Users\Aishwarya\Desktop\Datasets\cars.csv")
df

symboling normalized-losses         make fuel-type   body-style  \
0            3                 ?  alfa-romero       gas  convertible   
1            3                 ?  alfa-romero       gas  convertible   
2            1                 ?  alfa-romero       gas    hatchback   
3            2               164         audi       gas        sedan   
4            2               164         audi       gas        sedan   
..         ...               ...          ...       ...          ...   
200         -1                95        volvo       gas        sedan   
201         -1                95        volvo       gas        sedan   
202         -1                95        volvo       gas        sedan   
203         -1                95        volvo    diesel        sedan   
204         -1                95        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

    horsepower  city-mpg  highway-mpg  price  
0          111        21           27  13495  
1          111        21           27  16500  
2          154        19           26  16500  
3          102        24           30  13950  
4          115        18           22  17450  
..         ...       ...          ...    ...  
200        114        23           28  16845  
201        160        19           25  19045  
202        134        18           23  21485  
203        106        26           27  22470  
204        114        19           25  22625  

[205 rows x 15 columns]

In [4]:
df.replace("?", np.nan, inplace=True)

In [5]:
df

symboling normalized-losses         make fuel-type   body-style  \
0            3               NaN  alfa-romero       gas  convertible   
1            3               NaN  alfa-romero       gas  convertible   
2            1               NaN  alfa-romero       gas    hatchback   
3            2               164         audi       gas        sedan   
4            2               164         audi       gas        sedan   
..         ...               ...          ...       ...          ...   
200         -1                95        volvo       gas        sedan   
201         -1                95        volvo       gas        sedan   
202         -1                95        volvo       gas        sedan   
203         -1                95        volvo    diesel        sedan   
204         -1                95        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

    horsepower  city-mpg  highway-mpg  price  
0          111        21           27  13495  
1          111        21           27  16500  
2          154        19           26  16500  
3          102        24           30  13950  
4          115        18           22  17450  
..         ...       ...          ...    ...  
200        114        23           28  16845  
201        160        19           25  19045  
202        134        18           23  21485  
203        106        26           27  22470  
204        114        19           25  22625  

[205 rows x 15 columns]

In [6]:
si = SimpleImputer()

df.iloc[:,[1,11]] = si.fit_transform(df.iloc[:,[1,11]])
df

symboling  normalized-losses         make fuel-type   body-style  \
0            3              122.0  alfa-romero       gas  convertible   
1            3              122.0  alfa-romero       gas  convertible   
2            1              122.0  alfa-romero       gas    hatchback   
3            2              164.0         audi       gas        sedan   
4            2              164.0         audi       gas        sedan   
..         ...                ...          ...       ...          ...   
200         -1               95.0        volvo       gas        sedan   
201         -1               95.0        volvo       gas        sedan   
202         -1               95.0        volvo       gas        sedan   
203         -1               95.0        volvo    diesel        sedan   
204         -1               95.0        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

     horsepower  city-mpg  highway-mpg  price  
0         111.0        21           27  13495  
1         111.0        21           27  16500  
2         154.0        19           26  16500  
3         102.0        24           30  13950  
4         115.0        18           22  17450  
..          ...       ...          ...    ...  
200       114.0        23           28  16845  
201       160.0        19           25  19045  
202       134.0        18           23  21485  
203       106.0        26           27  22470  
204       114.0        19           25  22625  

[205 rows x 15 columns]

In [10]:
cat_cols = df.select_dtypes(object).columns
cat_cols

Index(['make', 'fuel-type', 'body-style', 'drive-wheels', 'engine-location',
       'engine-type'],
      dtype='object')

In [11]:
oe = OrdinalEncoder()

df[cat_cols] = oe.fit_transform(df[cat_cols])
df

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
0            3              122.0   0.0        1.0         0.0           2.0   
1            3              122.0   0.0        1.0         0.0           2.0   
2            1              122.0   0.0        1.0         2.0           2.0   
3            2              164.0   1.0        1.0         3.0           1.0   
4            2              164.0   1.0        1.0         3.0           0.0   
..         ...                ...   ...        ...         ...           ...   
200         -1               95.0  21.0        1.0         3.0           2.0   
201         -1               95.0  21.0        1.0         3.0           2.0   
202         -1               95.0  21.0        1.0         3.0           2.0   
203         -1               95.0  21.0        0.0         3.0           2.0   
204         -1               95.0  21.0        1.0         3.0           2.0   

     engine-location  width  height  engine-type  engine-size  horsepower  \
0                0.0   64.1    48.8          0.0          130       111.0   
1                0.0   64.1    48.8          0.0          130       111.0   
2                0.0   65.5    52.4          5.0          152       154.0   
3                0.0   66.2    54.3          3.0          109       102.0   
4                0.0   66.4    54.3          3.0          136       115.0   
..               ...    ...     ...          ...          ...         ...   
200              0.0   68.9    55.5          3.0          141       114.0   
201              0.0   68.8    55.5          3.0          141       160.0   
202              0.0   68.9    55.5          5.0          173       134.0   
203              0.0   68.9    55.5          3.0          145       106.0   
204              0.0   68.9    55.5          3.0          141       114.0   

     city-mpg  highway-mpg  price  
0          21           27  13495  
1          21           27  16500  
2          19           26  16500  
3          24           30  13950  
4          18           22  17450  
..        ...          ...    ...  
200        23           28  16845  
201        19           25  19045  
202        18           23  21485  
203        26           27  22470  
204        19           25  22625  

[205 rows x 15 columns]

In [12]:
x = df.iloc[:,:-1]
y = df['price']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3, random_state=1)

In [17]:
lr = LinearRegression()
lr.fit(xtrain,ytrain)
ypred = lr.predict(xtest)

print(f"Train Accuracy is {lr.score(xtrain,ytrain) }\nTest Accuracy is {lr.score(xtest,ytest)}")

Train Accuracy is 0.8504573774895472
Test Accuracy is 0.7965566780397382


In [18]:
lr.coef_

array([ 4.51384957e+01,  1.53127607e+00, -2.00099087e+02, -6.22650015e+02,
       -1.70235175e+02,  1.86860719e+03,  1.64133620e+04,  7.89452171e+02,
        3.62663990e+02,  2.83174279e+02,  9.83682875e+01, -1.08169245e+01,
        3.08017854e+02, -4.17024371e+02])

# Lasso

In [21]:
l1 = Lasso(alpha=1)
l1.fit(xtrain,ytrain)

print(f"Train Accuracy is {l1.score(xtrain,ytrain) }\nTest Accuracy is {l1.score(xtest,ytest)}")

Train Accuracy is 0.8504560242712866
Test Accuracy is 0.7967303673537032


In [22]:
l1.coef_

array([ 4.49259347e+01,  1.53240659e+00, -1.99923068e+02, -6.14190997e+02,
       -1.71341059e+02,  1.86538556e+03,  1.63433231e+04,  7.87471142e+02,
        3.63257326e+02,  2.83240951e+02,  9.84589905e+01, -1.06994004e+01,
        3.06876373e+02, -4.15639005e+02])

# Hyperparameter Tuning

In [24]:
for i in range(100, 200):
    l1 = Lasso(alpha=i)
    l1.fit(xtrain,ytrain)
    
    print(f"{i} {l1.score(xtrain,ytrain)} {l1.score(xtest,ytest)}")

100 0.8372922869101472 0.8089989519118683
101 0.8370340019654077 0.8090893744316343
102 0.8367731493417812 0.8091789601051912
103 0.8365097288233735 0.8092677091597652
104 0.836243739759986 0.809355622090732
105 0.8359751820764018 0.809442698991254
106 0.8357039606128402 0.8095289994157535
107 0.835430264846456 0.8096144037402809
108 0.8351539996558349 0.8096989726368534
109 0.8348751651768811 0.8097827060334882
110 0.8345936598074987 0.8098656626873878
111 0.834309686363372 0.8099477241988432
112 0.8340231435665733 0.8100289502941956
113 0.8337340313847619 0.8101093409999014
114 0.833442241613059 0.8101889541347452
115 0.8331479903445225 0.8102676731159629
116 0.8328511695893421 0.8103455567944016
117 0.8325517792978195 0.8104226051983998
118 0.8322497046473162 0.8104988749770783
119 0.8319451752671276 0.8105742517223582
120 0.8316380765758711 0.8106487931098093
121 0.8313284080285195 0.8107224994000667
122 0.8310160485813688 0.8107954256724004
123 0.8307012415940034 0.810867460069921

In [25]:
l1 = Lasso(alpha=170)
l1.fit(xtrain,ytrain)
print(f"Train Accuracy is {l1.score(xtrain,ytrain) }\nTest Accuracy is {l1.score(xtest,ytest)}")

Train Accuracy is 0.8130040832573873
Test Accuracy is 0.8133113351310719


In [26]:
l1.coef_

array([ 4.43490130e+00,  2.00056602e+00, -1.72066327e+02, -0.00000000e+00,
       -3.70073745e+02,  1.23453446e+03,  4.27843994e+03,  3.99653319e+02,
        4.53832760e+02,  3.01208227e+02,  1.13098477e+02,  1.02575283e+01,
        8.04028285e+01, -1.69892755e+02])

# Ridge 

In [27]:
l2 = Ridge()
l2.fit(xtrain,ytrain)

print(f"Train Accuracy is {l2.score(xtrain,ytrain) }\nTest Accuracy is {l2.score(xtest,ytest)}")

Train Accuracy is 0.8436019887231634
Test Accuracy is 0.8074518758147271


In [28]:
for i in range(1,50):
    l2 = Ridge(alpha=i)
    l2.fit(xtrain,ytrain)
    print(f"{i} {l2.score(xtrain,ytrain)} {l2.score(xtest,ytest)}")

1 0.8436019887231634 0.8074518758147271
2 0.8356568294333326 0.8110292248150515
3 0.829596685378384 0.8126933383890032
4 0.8250050456621351 0.8136148645029299
5 0.8214255248858179 0.8141745853539419
6 0.8185497905642731 0.8145301242133357
7 0.8161775446879697 0.8147582608502812
8 0.8141763553347593 0.8149010602831953
9 0.8124561449821562 0.8149836949253052
10 0.8109538582620315 0.8150222867376525
11 0.8096241695970483 0.8150277245431792
12 0.8084337140523127 0.8150076788279419
13 0.8073574061115951 0.8149677381788261
14 0.8063760269401786 0.8149120868051176
15 0.8054746030665225 0.8148439278252516
16 0.8046412917341841 0.814765758494739
17 0.8038665985400391 0.8146795554128126
18 0.8031428178838972 0.8145869029046835
19 0.8024636258876571 0.8144890843369585
20 0.8018237796035674 0.814387148544555
21 0.8012188915864451 0.8142819591129825
22 0.8006452587395116 0.8141742315788493
23 0.8000997308073307 0.8140645619421538
24 0.7995796082141258 0.8139534488166058
25 0.7990825618875559 0.8138

In [29]:
l2 = Ridge(alpha=10)
l2.fit(xtrain,ytrain)

print(f"Train Accuracy is {l2.score(xtrain,ytrain) }\nTest Accuracy is {l2.score(xtest,ytest)}")

Train Accuracy is 0.8109538582620315
Test Accuracy is 0.8150222867376525


# Elastic Net

In [30]:
en = ElasticNet()

en.fit(xtrain,ytrain)
print(f"Train Accuracy is {en.score(xtrain,ytrain) }\nTest Accuracy is {en.score(xtest,ytest)}")

Train Accuracy is 0.7865776086026621
Test Accuracy is 0.8094188583631502
